---
apiVersion: v1 
kind: Pod
metadata:
  name: alpineconfing-env
spec:
  containers: 
    - name: alpine
      image: alpine
      envFrom:
        - configMapRef:
            - name: dummyconfigmap
              optional: false
      args:
        - sleep
        - 1d