---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqlrp 
  labels:
    app: mysql
spec:
  minReadySeconds: 1
  replicas: 2
  selector: 
    matchLabels:
      app: mysql
  template: 
    metadata: 
      name: mysqlrp
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports: 
            - containerPort: 3306
          envFrom:
            configMapRef:
              name: mysqlconfigmap
          volumeMounts: 
            name: mysqlvol
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysqlvol
      spec:
        accessModes: 
          - ReadWriteOnce
        storageClassName: managed
        resources:
          requests:
            storage: 1Gi


