---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
    type: ClusterIP
    ports:
      name: mysql-svc
      port: 80
      targetPort: 3306
      protocol: TCP
