---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-volumes
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:latest
      ports:
        - containerPort: 3306
      volumeMounts: 
        name: mypvc-vol
        mountPath: /var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employee
        - name: MYSQL_USER
          value: abhish
        - name: MYSQL_PASSWORD
          value: rootroot
  volumes:
    - name: mypvc-vol
      persistentVolumeClaim:
        claimName: mysql-pvc