---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
spec:
  minReadySeconds: 1
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80