---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels: 
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: htmlvol
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: htmlvol
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: managed
        resources:
          requests:
            storage: 1Gi