---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-ds
  annotations:
    kubernetes.io/change-cause: "addedn fluentd"
spec:
  minReadySeconds: 3
  selector:
    matchLabels:
      app: fluentd
    template:
      metadata:
        name: fluentd
        labels:
          app: fluentd
    spec:
      containers:
        - name: filentd
          image: fluentd:latest