---
apiVersion: v1 
kind: Pod
metadata:
  name: nodeselector
  labels:
    app: nodeselector
spec:
  nodeSelector:  ### Nodes can be selected by providing the name or labels
    nodename: "api_server"
  containers:
    - name: nginx
      image: nginx:latest