---
apiVersion: v1 
kind: Pod
metadata:
  name: nodeselector
  labels:
    app: nodeselector
spec:
  nodeName: "azks-vm-00001" ### Nodes can be selected by providing the name or labels
  containers:
    - name: nginx
      image: nginx:latest